version: '3.1'

services:

  mongo-io:
    image: mongo
    restart: always
    ports:
      - 20000:27017
    env_file:
      ./io_db/db.env
    # networks:
    #   - cli-rpg-io-mongo

  mongo-express-io:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      ./io_db/db.env
    # networks:
    #   - cli-rpg-io-mongo

  io_service:
    depends_on:
      - mongo
    image: io_service
    ports:
      - 5001:5000
    restart: always
    build: ./io_service
    env_file:
      ./io_service/io_service.env


networks:
  cli-rpg-io-mongo: