version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 20000:27017
    env_file:
      db.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      db.env